// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNvh5xMRJLdNq_ofiP9NJPvNpsrCf4Psw',
    appId: '1:947285203602:web:512eb17285af2dd216644b',
    messagingSenderId: '947285203602',
    projectId: 'our-beutiful-love',
    authDomain: 'our-beutiful-love.firebaseapp.com',
    storageBucket: 'our-beutiful-love.firebasestorage.app',
    measurementId: 'G-6FKXGDDHJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBM0oErSXJr2i4welSFggk3fWJ-gWLFcZ4',
    appId: '1:947285203602:android:d1d0661a8318bcee16644b',
    messagingSenderId: '947285203602',
    projectId: 'our-beutiful-love',
    storageBucket: 'our-beutiful-love.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9myKfgv-mLeKdUb_y6Rqbp8y7nW3PlgY',
    appId: '1:947285203602:ios:52dbad43ac54883a16644b',
    messagingSenderId: '947285203602',
    projectId: 'our-beutiful-love',
    storageBucket: 'our-beutiful-love.firebasestorage.app',
    iosBundleId: 'com.example.ourBeutifulLove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9myKfgv-mLeKdUb_y6Rqbp8y7nW3PlgY',
    appId: '1:947285203602:ios:52dbad43ac54883a16644b',
    messagingSenderId: '947285203602',
    projectId: 'our-beutiful-love',
    storageBucket: 'our-beutiful-love.firebasestorage.app',
    iosBundleId: 'com.example.ourBeutifulLove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNvh5xMRJLdNq_ofiP9NJPvNpsrCf4Psw',
    appId: '1:947285203602:web:243c3db322e143cd16644b',
    messagingSenderId: '947285203602',
    projectId: 'our-beutiful-love',
    authDomain: 'our-beutiful-love.firebaseapp.com',
    storageBucket: 'our-beutiful-love.firebasestorage.app',
    measurementId: 'G-JTXVTKX01N',
  );
}
